# Generated by Django 5.1.5 on 2025-03-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cx_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cxpipeline',
            name='status',
            field=models.CharField(choices=[('lead', 'Lead/Prospect'), ('negotiation', 'Negotiation'), ('onboarding', 'Onboarding'), ('active', 'Active Engagement'), ('closed', 'Renewal/Closure')], default='lead', max_length=50),
        ),
    ]
