# Generated by Django 5.1.5 on 2025-03-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cx_pipeline', '0002_alter_cxpipeline_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cxpipeline',
            name='current_stage',
        ),
        migrations.AlterField(
            model_name='cxpipeline',
            name='status',
            field=models.IntegerField(choices=[(1, 'Lead/Prospect'), (2, 'Negotiation'), (3, 'Onboarding'), (4, 'Active Engagement'), (5, 'Renewal/Closure')], default=1),
        ),
        migrations.DeleteModel(
            name='PipelineStage',
        ),
    ]
