# Generated by Django 5.1.5 on 2025-03-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cx_pipeline', '0005_cxpipeline_stage_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cxpipeline',
            name='expected_duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Expected duration of the pipeline in days', null=True),
        ),
    ]
