# Generated by Django 5.1.5 on 2025-02-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('high_spenders', 'High Spenders'), ('moderate_spenders', 'Moderate Spenders'), ('low_spenders', 'Low Spenders'), ('active_users', 'Active Users'), ('inactive_users', 'Inactive Users'), ('at_risk_users', 'At-Risk Users')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='segments',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='marketing.segment'),
        ),
    ]
