# Generated by Django 5.1.5 on 2025-02-13 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_segment_campaign_segments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='segments',
        ),
        migrations.DeleteModel(
            name='Segment',
        ),
    ]
