# Generated by Django 5.1.5 on 2025-03-03 11:34

from django.db import migrations, models
import django.utils.timezone

def set_default_created_at(apps, schema_editor):
    CxClient = apps.get_model('auth_app', 'CxClient')
    for client in CxClient.objects.all():
        client.created_at = django.utils.timezone.now()
        client.save()

class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_cxclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='cxclient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),  # Temporarily allow null
        ),
        migrations.RunPython(set_default_created_at),
        migrations.AlterField(
            model_name='cxclient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),  # Remove null=True after populating
        ),
    ]
