# Generated by Django 5.1.5 on 2025-03-25 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calllog',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='calllog',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='caller_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calllog',
            name='currency_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='destination_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calllog',
            name='hangup_cause',
            field=models.CharField(blank=True, choices=[('NORMAL_CLEARING', 'Normal Clearing'), ('CALL_REJECTED', 'Call Rejected'), ('NO_ANSWER', 'No Answer'), ('USER_BUSY', 'User Busy'), ('UNALLOCATED_NUMBER', 'Unallocated Number'), ('ORIGINATOR_CANCEL', 'Originator Cancel'), ('LOSE_RACE', 'Lose Race'), ('SERVICE_UNAVAILABLE', 'Service Unavailable'), ('UNSPECIFIED', 'Unspecified')], max_length=50, null=True),
        ),
    ]
