# Generated by Django 5.1.5 on 2025-03-28 12:54

import call_center.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0004_queuedcall_agentstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queuedcall',
            options={'ordering': ['timestamp'], 'verbose_name': 'Queued Call', 'verbose_name_plural': 'Queued Calls'},
        ),
        migrations.AlterField(
            model_name='queuedcall',
            name='caller_number',
            field=models.CharField(blank=True, default='unknown_caller', help_text="Caller's phone number", max_length=20),
        ),
        migrations.AlterField(
            model_name='queuedcall',
            name='session_id',
            field=models.CharField(default=call_center.models.generate_session_id, help_text='Unique call session identifier', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='queuedcall',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='waiting', help_text='Current status of the queued call', max_length=20),
        ),
        migrations.AlterField(
            model_name='queuedcall',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='When the call was queued'),
        ),
        migrations.AddIndex(
            model_name='queuedcall',
            index=models.Index(fields=['session_id'], name='call_center_session_271dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='queuedcall',
            index=models.Index(fields=['status'], name='call_center_status_b7a451_idx'),
        ),
    ]
